### ISSUE TITLE
Ranks

### ISSUE THREAD

**Issue by Refrac** [Yochran/yoCore#17]
It would be cool if you could disable Ranks if you were using a plugin like LuckPerms for permission handling. If this is a feature already please let me know.

**Comment by Yochran** [comment]
Ranks are essential to the entire rest of the plugin, regarding your name, rank display and prefix, which affects your nametags, how you appear in chat, the staff chat formats, etc.

`   public String getColor() { return getRank().getColor(); }
    public String getDisplayName() { return getColor() + getPlayer().getName(); }
    public String getDisplayNickname() { return plugin.getConfig().getString("Nickname.NickPrefix") + getNickname(); }
    public String getPrefix() { return getRank().getPrefix(); }`
