### ISSUE TITLE
Network Connection

### ISSUE THREAD

**Issue by IceK1203** [Yochran/yoCore#2]
How do I connect the plugin to multiple servers on my Network is it true MySQL or Mongo and Redis? please help and give me a good way how to do this (PS BIG FAN!!)

**Comment by Yochran** [comment]
This plugin is not bungeecord, it is never stated to be.

**Comment by IceK1203** [comment]
Well Its an amzing plugin and would be the best core possible ever if it were to be Bungee compatable using Mongo & Redis or MySQL, Could this be possible in a future Update?

**Comment by Yochran** [comment]
This has already been answered on spigot, I have no urgent plans to make this plugin bungee compatible.

**Comment by IceK1203** [comment]
I understand, but if you do put in the effort this could change the COre community forever, and you could and most likely will be one of the top devs easily beating Faceslap and others

**Comment by IceK1203** [comment]
nun the less the reason why I ask is because I own a network and this would be amazing if it was Bungee compatable plssssss if you can update it, thank u
