### ISSUE TITLE
Can't add more then 14 ranks

### ISSUE THREAD

**Issue by frede69** [Yochran/yoCore#23]
when i add more then 14 ranks, it wont show in the grant gui...

**Comment by VaguerCrown3732** [comment]
bruh

**Comment by Yochran** [comment]
Show me your config file. I made 15 and it worked just fine:
![image](https://user-images.githubusercontent.com/71285258/216732285-07aa7e03-d0e2-4c0a-b339-07306112b2d2.png)
![image](https://user-images.githubusercontent.com/71285258/216732305-3f44ff1e-9b1f-43c5-9802-640c8acbf140.png)

**Comment by VaguerCrown3732** [comment]
How do you make more slots in the grant menu like make the grant inventory thing bigger

**Comment by Yochran** [comment]
You can't, it's 9 as a maximum. That's why the GUI is paged.
