### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by VaguerCrown3732** [Yochran/yoCore#26]
Whenever I star the server this is what it says:
155 [21:41:13] [Server thread/INFO]: [yoCore] Enabling yoCore v1.0.1
156 | [21:41:13] [Server thread/INFO]: yoCore v1.0 by Yochran is loading...
157 | [21:41:13] [Server thread/INFO]: **Server permissions file permissions.yml is empty, ignoring it**
158 | [21:41:13] [Server thread/INFO]: Done (17.633s)! For help, type "help"
Then when I op myself and try a command the console go crazy with errors please help

**Comment by Yochran** [comment]
That's not a yoCore issue. Your server's permissions.yml file is empty meaning op doesn't work.
