### ISSUE TITLE
Not Loading - YoCore

### ISSUE THREAD

**Issue by funkyranveer** [Yochran/yoCore#9]
I've restarted and replaced continuously YoCore in my server to try to get it to work and it just never loads. I even have all the right files to run it

**Comment by InfinitysGithub** [comment]
Same!

**Comment by Yochran** [comment]
Can you look for any errors in console?

**Comment by funkyranveer** [comment]
There are non, I've check with all developers I could find. To add to this the files load all correct and the cmd's are in-game but as I said it never works

**Comment by Yochran** [comment]
You (or a staff member) may have done something to corrupt one of the config files. You may have to reset all of them. However, since there are no errors, save a backup of all of the config files so that if that's not the issue, you can put them back.

**Comment by funkyranveer** [comment]
Hello Yochran/yoCore,
I have already had a look multiple times. I even got some developers to
check for me but they couldn't find any errors due to the commands loading
in-game but never working.

**Comment by Yochran** [comment]
Then it must be that you didn't follow the installation guide properly.
